export default {
  devlog: {
    fn: 'log',
    color: 'appBase',
    devOnly: true,
    includeTime: true,
    includeDiff: true,
  },
  info: {
    fn: 'info',
    icon: 'ℹ',
    suffix: 'Info:',
    color: 'ltBlueV',
    devOnly: false,
    includeTime: false,
    includeDiff: false,
  },
  warn: {
    fn: 'warn',
    icon: '⚠',
    suffix: 'WARN:',
    color: 'orangeT',
    height: '35px',
    devOnly: false,
    includeTime: false,
    includeDiff: false,
  },
  error: {
    fn: 'error',
    icon: '❕',
    suffix: 'ERROR:',
    color: 'redT',
    height: '35px',
    devOnly: false,
    includeTime: true,
    includeDiff: false,
  },
  trace: {
    fn: 'trace',
    suffix: 'trace:',
    color: 'cyanT',
    devOnly: true,
    includeTime: true,
    includeDiff: true,
  },
  success: {
    fn: 'log',
    icon: '✅',
    suffix: 'Success:',
    color: 'emeraldT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  magenta: {
    fn: 'log',
    color: 'magenta',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  red: {
    fn: 'log',
    color: 'redV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  pink: {
    fn: 'log',
    color: 'pinkV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  purple: {
    fn: 'log',
    color: 'purpleV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  deepPurple: {
    fn: 'log',
    color: 'deepPurpleV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  indigo: {
    fn: 'log',
    color: 'indigoV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  blue: {
    fn: 'log',
    color: 'blueV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  ltBlue: {
    fn: 'log',
    color: 'ltBlueV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  cyan: {
    fn: 'log',
    color: 'cyanV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  teal: {
    fn: 'log',
    color: 'tealV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  green: {
    fn: 'log',
    color: 'greenV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  ltGreen: {
    fn: 'log',
    color: 'ltGreenV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  lime: {
    fn: 'log',
    color: 'limeV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  yellow: {
    fn: 'log',
    color: 'yellowV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  amber: {
    fn: 'log',
    color: 'amberV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  orange: {
    fn: 'log',
    color: 'orangeV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  deepOrange: {
    fn: 'log',
    color: 'deepOrangeV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  brown: {
    fn: 'log',
    color: 'brownV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  blueGrey: {
    fn: 'log',
    color: 'blueGreyV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  grey: {
    fn: 'log',
    color: 'greyV',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  slate: {
    fn: 'log',
    color: 'slateT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  gray: {
    fn: 'log',
    color: 'grayT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  zinc: {
    fn: 'log',
    color: 'zincT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  neutral: {
    fn: 'log',
    color: 'neutralT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  stone: {
    fn: 'log',
    color: 'stoneT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  redT: {
    fn: 'log',
    color: 'redT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  orangeT: {
    fn: 'log',
    color: 'orangeT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  amberT: {
    fn: 'log',
    color: 'amberT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  yellowT: {
    fn: 'log',
    color: 'yellowT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  limeT: {
    fn: 'log',
    color: 'limeT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  greenT: {
    fn: 'log',
    color: 'greenT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  emeraldT: {
    fn: 'log',
    color: 'emeraldT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  tealT: {
    fn: 'log',
    color: 'tealT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  cyanT: {
    fn: 'log',
    color: 'cyanT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  skyT: {
    fn: 'log',
    color: 'skyT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  blueT: {
    fn: 'log',
    color: 'blueT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  indigoT: {
    fn: 'log',
    color: 'indigoT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  violetT: {
    fn: 'log',
    color: 'violetT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  purpleT: {
    fn: 'log',
    color: 'purpleT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  fuchsiaT: {
    fn: 'log',
    color: 'fuchsiaT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  pinkT: {
    fn: 'log',
    color: 'pinkT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
  roseT: {
    fn: 'log',
    color: 'roseT',
    devOnly: true,
    includeTime: false,
    includeDiff: false,
  },
}
