export default function () {
  console.time.info('here is some info with the time')
  console.log('a regular log')
  console.trace('trace')
  console.start.gray('this is gray')
  console.pink('this is pink')
  setTimeout(function () {
    console.gray('this is still gray')
    console.stop.gray('this is still gray')
    console.gray('this is gray again')
    console.gray('this is still still  gray')
  }, 500)

  console.devlog('a dev log')
  console.error('Oh no!')
  console.warn('warning, warning')
  console.info('here is some info')
  console.success('YAY!')
  console.trace('trace')
  console.red('red color from vuetify')
  console.redT('red color from tailwind')
  console.roseT('rose color from tailwind')
  console.pink('pink color from vuetify')
  console.pinkT('pink color from tailwind')
  console.magenta('custom magenta color')
  console.fuchsiaT('fuchsia color from tailwind')
  console.violetT('violet color from tailwind')
  console.purple('purple color from vuetify')
  console.purpleT('purple color from tailwind')
  console.deepPurple('deep-purple color from vuetify')
  console.indigo('indigo color from vuetify')
  console.indigoT('indigo color from tailwind')
  console.blue('blue color from vuetify')
  console.blueT('blue color from tailwind')
  console.ltBlue('light-blue color from vuetify')
  console.skyT('sky color from tailwind')
  console.cyan('cyan color from vuetify')
  console.cyanT('cyan color from tailwind')
  console.teal('teal color from vuetify')
  console.tealT('teal color from tailwind')
  console.emeraldT('emerald color from tailwind')
  console.green('green color from vuetify')
  console.greenT('green color from tailwind')
  console.ltGreen('light-green color from vuetify')
  console.lime('lime color from vuetify')
  console.limeT('lime color from tailwind')
  console.yellow('yellow color from vuetify')
  console.yellowT('yellow color from tailwind')
  console.amber('amber color from vuetify')
  console.amberT('amber color from tailwind')
  console.orange('orange color from vuetify')
  console.orangeT('orange color from tailwind')
  console.deepOrange('deep-orange color from vuetify')
  console.brown('brown color from vuetify')
  console.blueGrey('blue-grey color from vuetify')
  console.grey('grey color from vuetify')
  console.slate('slate color from tailwind')
  console.gray('gray color from tailwind')
  console.zinc('zinc color from tailwind')
  console.neutral('neutral color from tailwind')
  console.stone('stone color from tailwind')

  console.time.gray('I did it!')
  console.td.gray('I did it!')
  console.gray('I did it!')
  console.lastTime['gray'] = null
  console.diff.gray('I did it!')
  console.gray('I did a reset!')
  console.diff.gray('I did it!')

  for (const [key, value] of Object.entries(console)) {
    if (typeof value === 'function' && key != 'clear') {
      value(key)
      console.log(`${key}: ${value}`)
    }
  }
}
